version: "3.3"

services:
  web:
    build: go
    image: crypto/web
    container_name: web
    environment:
      DB_HOST: db
      DB_USERNAME: crypto
      DB_PASSWORD: crypto
      DB_DATABASE: crypto
    restart: always
    ports:
      - "80:8181"
    volumes:
      - ../:/app
    networks:
      - crypto
    depends_on:
      - db

  db:
    build: postgres
    image: crypto/db
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
      - "./volumes/data:/opt/data"
    tmpfs:
      - /run
      - /tmp
    ports:
      - "5432:5432"
    networks:
      - crypto

networks:
  crypto:
    external: true